export const SIGNUP = "SIGNUP";
export const SIGNUP_PENDING = "SIGNUP_PENDING";
export const SIGNUP_FULFILLED = "SIGNUP_FULFILLED";
export const SIGNUP_REJECTED = "SIGNUP_REJECTED";

export const SIGNIN = "SIGNIN";
export const SIGNIN_PENDING = "SIGNIN_PENDING";
export const SIGNIN_FULFILLED = "SIGNIN_FULFILLED";
export const SIGNIN_REJECTED = "SIGNIN_REJECTED";

export const GET_USER = "GET_USER";
export const GET_USER_PENDING = "GET_USER_PENDING";
export const GET_USER_FULFILLED = "GET_USER_FULFILLED";
export const GET_USER_REJECTED = "GET_USER_REJECTED";

export const SIGNOUT = "SIGNOUT";
